# Generated by Django 5.2.3 on 2025-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreateForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option1", models.CharField(max_length=50)),
                ("option2", models.CharField(max_length=50)),
                ("option3", models.CharField(max_length=50)),
            ],
        ),
    ]
