# Generated by Django 5.2.3 on 2025-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="createform",
            old_name="option3",
            new_name="option_One",
        ),
        migrations.RenameField(
            model_name="createform",
            old_name="option1",
            new_name="option_Three",
        ),
        migrations.RenameField(
            model_name="createform",
            old_name="option2",
            new_name="option_Two",
        ),
        migrations.AlterField(
            model_name="createform",
            name="question",
            field=models.CharField(max_length=200),
        ),
    ]
