# Generated by Django 5.2.3 on 2025-07-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0002_rename_option3_createform_option_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createform",
            name="option_one_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="createform",
            name="option_three_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="createform",
            name="option_two_count",
            field=models.IntegerField(default=0),
        ),
    ]
